cv/urls.py
from django.urls import path

from .views import*

app_name = 'cv'

urlpatterns = [
    path('', aboutMe.as_view(), name='aboutMe'),
    path('aboutMe/', aboutMe.as_view(), name = 'aboutMe'),
    path('experience/', experience.as_view(), name='experience'),
    path('portfolio/', portfolio.as_view(), name='portfolio'),
    path('contactMe/', contactMe.as_view(), name='contactMe'),
    path('secondPage/', secondPage.as_view(), name='secondPage'),

]

schedule/urls.py
from django.urls import path, re_path
from .views import *

app_name = "schedule"

urlpatterns = [
    path('', landing),
    path('landing', landing, name='landing'),
    path('delete', delete),
    path('create', inputPage),
    path('sched', sched, name='sched')
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cv.urls')),
    path('schedule/', include('schedule.urls')),
]

cv/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models
import datetime
# Create your models here.

class Schedule(models.Model):
    category = models.CharField(max_length=50, default="Random")
    event = models.CharField(max_length = 50)
    place = models.CharField(max_length = 50)
    day = models.CharField(max_length = 20)
    date = models.DateField()
    jam = models.TimeField()

    def __str__(self):
        return self.event

    def date_day(self):
        new_tanggal = str(self.date)
        year, month, day = map(int,new_tanggal.split('-'))

        new_month = datetime.date(year, month, day).strftime("%B")

        if(day == 1):
            new_day = "1st"
        elif(day == 2):
            new_day = "2nd"
        elif(day==3):
            new_day = "3rd"
        else:
            new_day = str(day) + "th"

        return self.day + ', ' + str(new_month) + " " + str(new_day) + " " + str(year) 


    def time(self):
        return str(self.jam)

schedule/forms.py
from django import forms

from .models import Schedule

class ScheduleForm(forms.Form):

    categoryForm = forms.CharField(label = "category", help_text = 'Please input the category of the event')

    eventForm = forms.CharField(label = 'Event',
    help_text = 'Please input the event')

    placeForm = forms.CharField(label='Place', required=False)

    dateForm = forms.CharField(label='Date', help_text = 'Enter a date in MM-DD-YYYY format')

    timeForm = forms.TimeField(label='Time', help_text = 'Entar a time in Hour:Minute:Seconds format')

cv/views.py
from django.views.generic import TemplateView

class aboutMe(TemplateView):
    template_name ='aboutMe.html'

class experience(TemplateView):
    template_name = 'experience.html'

class portfolio(TemplateView):
    template_name = 'portfolio.html'

class contactMe(TemplateView):
    template_name = 'contactMe.html'
    
class secondPage(TemplateView):
    template_name = 'secondPage.html'

schedule/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.http import HttpResponse

from .forms import ScheduleForm
from .models import Schedule

import datetime

# Create your views here.
def landing(request):
    return render(request, 'mainSchedule.html')

def inputPage(request):
    form = ScheduleForm()

    if request.method == "POST":
        form = ScheduleForm(request.POST)

        print(form.errors)
        if form.is_valid():
            day, month, year = map(int, request.POST['dateForm'].split('-'))
            Schedule.objects.create(
                category = request.POST['categoryForm'],
                event = request.POST['eventForm'],
                place = request.POST['placeForm'],
                day = datetime.date(day, month, year).strftime('%A'),
                date = request.POST['dateForm'],
                jam = request.POST['timeForm']
            )

            return HttpResponseRedirect('sched')

        
       

    context = {
        'form':form
    }
    return render(request, "inputPage.html",context)


def sched(request):
    schedData = Schedule.objects.all()
    context = {
        'CONTENT': schedData
    }
    return render(request, 'schedule.html', context)


def delete(request):
    if request.method == "POST":
        id = request.POST['id']
        Schedule.objects.get(id=id).delete()
    return sched(request)

cv/templates/aboutMe.html
{% extends "base.html" %}
{%load static%}
{% block title %}About Rofi{% endblock %}

{% block content %}
<div class="container" id="aboutMe">
    <h1>Hi! I am Abdurrafi Arief</h1>
    <img class="card-image responsive-img" src="{% static 'cv/cutefoto.jpg' %}" id="editedFotosize">
    <div class="flow-text">I am a computer science student from the University of Indonesia, the Faculty of Computer Science. Currently I am learning web design and this website is one of my projects this semester. I am interested in coding problems and learning more about computer science. </div>

    <h4>Skills</h4>
    <p id="skillsIcons"><i class="fab fa-python"></i>               <i class="fab fa-java"></i>              <i class="fab fa-html5"></i></p>

  </div>
{% endblock %}

cv/templates/base.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'cv/materialize.min.css'%}"  media="screen,projection"/>
    <!--Let browser know website is optimized for mobile-->
    <!--Import personal css-->
    <link type="text/css" rel="stylesheet" href="{% static 'cv/story3.css' %}" media="screen,projection"/>
    <!--Import stylesheet for icons-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% block title %}{% endblock %}</title>
  </head>

  <body>
    
    <!--Top Navbar-->
    <nav class="nav-extended">
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">Rofi</a>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li><a href="{% url 'cv:aboutMe'%}">About Me</a></li>
              <li><a href="{% url 'cv:experience'%}">My Experience</a></li>
              <li><a href="{% url 'cv:portfolio'%}">Portfolio</a></li>
              <li><a href="{% url 'cv:contactMe'%}">Contact Me</a></li>
              <li><a href="{% url 'schedule:landing'%}">My Schedule</a></li>
              <li><a href="{% url 'cv:secondPage'%}">A Mystery..</a></li>
          </ul>
        </div>
      </nav>
    <!--
      <ul class="sidenav" id="mobile-demo" style="transform: translateX(0%);">
          <li><a href="{% url 'cv:aboutMe'%}">About Me</a></li>
          <li><a href="{% url 'cv:experience'%}">My Experience</a></li>
          <li><a href="{% url 'cv:portfolio'%}">Portfolio</a></li>
          <li><a href="{% url 'cv:contactMe'%}">Contact Me</a></li>
          <li><a href="{% url 'cv:secondPage'%}">A Mystery..</a></li>
      </ul> -->
      {% block content %} {% endblock%}


    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="{% static 'cv/materialize.min.js' %}"></script>
  </body>
</html>

cv/templates/contactMe.html
{% extends "base.html" %}

{% block title %}Contact Rofi{% endblock %}

{% block content %}
<div class="container" id="contactMe">
    <h1>Contact Me!</h1>
    <div class="flow-text">Contact Me: 01231008329</div>
    <p id="contactMeIcons"><i class="fab fa-twitter-square"></i>  <i class="fab fa-instagram"></i> <i class="fab fa-gitlab"></i> <i class="fab fa-linkedin"></i></p>

  </div>
{% endblock %}

cv/templates/experience.html
{% extends "base.html" %}

{% block title %}Rofi's Experience{% endblock %}

{% block content %}
<div class="container" id="experience">
    <h1>My Experience</h1>
    <h4>BEM Fasilkom UI</h4>
    <div class="flow-text">
      Staff of Action and Strategical Departement where we raise awareness of Fasilkom students about sosial and political issues
    </div>
    <h4>FUKI Fasilkom UI</h4>
    <div class="flow-text">Staff of Creative Syiar Division where we try to creatively spread awareness of Islam to Fasilkom students.</div>
    <h4>PMB Fasilkom UI</h4>
    <div class="flow-text">Mentor for new university students, where I counsel and help them adapt to university life.</div>
  </div>
{% endblock %}

cv/templates/portfolio.html
{% extends "base.html" %}

{% block title %}Rofi's Portfolio{% endblock %}

{% block content %}
<div class="container" id="portfolio">
    <h1>Portfolio</h1>
    <h4>Personal Website</h4>
    <div class="flow-text">This very website is one of my projects that is meant to show off my skills and share my experiences</div>
    <h4>Coming Soon!</h4>
    <div class="flow-text">Wait for my next project!</div>
  </div>

{% endblock %}

cv/templates/secondPage.html
{% extends "base.html" %}
{%load static%}

{% block title %}Mystery{% endblock %}

{% block content %}
    <body background="{% static 'cv/sky.jpg'%}">
        <h1 id="yellow">HAHA NOTHING IS OF IMPORTANCE HERE</h1>
        <div class="flow-text"><a href="{% url 'aboutMe' %}">Click here to go back</a></div>
      <!--JavaScript at end of body for optimized loading-->
      <script type="text/javascript" src="{% static 'cv/materialize.min.js' %}"></script>
    </body>

{%endblock%}

schedule/templates/inputPage.html
{%extends 'base.html'%}
{%load static%}



{% block content %}
<div class="container">
<form method="POST">
    {% csrf_token %}
    <div class="container">
        <h4>Event Category</h4>
        <small>Enter the activities category</small>
        {{form.categoryForm}}
    </div>
    <div class="container">
        <h4>Event Name</h4> 
        <small>Input the event name</small>
        {{form.eventForm}}
    </div>
    <div class="container">
            <h4>Event Location</h4> 
            <small>Input the event location</small>
            {{form.placeForm}}
        </div>
    <div class="container">
        <h4>Date</h4>
        <small>Input the date in YYYY-MM-DD format</small>
        {{form.dateForm}}
    </div>
    
    <div class="container">
        <h4>Time</h4>
        <small>Input the time in HH:MM:SS</small>
        {{form.timeForm}}
    </div>
    <div class="container">
    <button type = "submit" class = "btn waves-effect waves-light">Submit</button>
    </div>
</form>
</div>

{% endblock %}

schedule/templates/mainSchedule.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <h1> My Schedule </h1>
        <div class="flow-text">Hello! This is my app for practicing Django models and database, which I applied to make a simple schedule organizer for myself, Abdurrafi Arief. Enjoy!</div>
        <a class="waves-effect waves-light btn" href="/schedule/create" role="button">Create New Event</a>
        <a class ="waves-effect waves-light btn" href = "/schedule/sched" role="button">See my Schedule</a> 
    </div>

{% endblock %}

schedule/templates/schedule.html
{%extends 'base.html'%}
{% load static %}

{%block content%}

<div class="container">
    <div class="row">
        {% for event in CONTENT%}
        <div class="col">
            <div class="card" style = "width: 18rem;">
                
                <h5 class="card-title" style="font-weight: bold">{{event.event}}</h5>
                <h6 class="subheader">{{event.date_day}}</h6>
                 
                <div class="card-content">This {{event.category}} event will be held on {{event.time}} at {{event.place}}</div>
                <form action="delete" method="POST" >
                    {% csrf_token %}
                    <input type="hidden" value="{{ event.id }}" name="id" />
                    <input class="red button small" type="submit" value="Delete" />
                </form>

            </div>
        </div>
        {% endfor %}
    </div>
    <a class="waves-effect waves-light btn" href="/schedule/create" role="button">Create New Event</a>
</div>

{% endblock %}